server:
  port: 8084

spring:
  application:
    name: payment-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

payment:
  gateway:
    mock-enabled: true
    success-rate: 0.9
    processing-delay-ms: 1000

  currency:
    default: LKR
    supported: LKR,USD,EUR

  tax:
    rate: 0.15

  receipt:
    business:
      name: "Smart Parking Management System"
      address: "123 Smart City Avenue, Colombo 03, Sri Lanka"
      phone: "+94 11 234 5678"
      email: "support@smartparking.lk"

logging:
  level:
    lk.ijse.paymentservice: DEBUG